apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: springboot
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp-mongo
        image: parthlimbachia1985/spring-boot-mongo:14
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cm-springboot
              key: username
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: cm-springboot
              key: hostname
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-springboot
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: springapp-svc
  namespace: springboot
spec:
  type: ClusterIP
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: springboot
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.24
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cm-springboot
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-springboot
              key: password
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongovol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: springboot
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

